library(BiocManager)
BiocManager::install(c(
  "affxparser", "affy", "affyio", "affyPLM", "altcdfenvs", "annaffy",
  "annotate", "AnnotationDbi", "aroma.light", "arules", "backports",
  "bayesm", "BayesX", "baySeq", "BB", "beachmat", "Biobase", "BiocGenerics",
  "BiocManager", "BiocParallel", "BiocVersion", "biocViews", "biomaRt",
  "Biostrings", "BMA", "bookdown", "bridge", "BSgenome", "bsseq",
  "BufferedMatrix", "BufferedMatrixMethods", "calibrate", "callr", "car",
  "CBPS", "checkpoint", "chron", "classInt", "cmprsk", "coin",
  "compositions", "curl", "data.table", "ddalpha", "DelayedArray",
  "DelayedMatrixStats", "Deriv", "DESeq", "DESeq2", "devtools", "digest",
  "DNAcopy", "doBy", "doFuture", "DSS", "DT", "dtw", "DynDoc", "Ecdat",
  "EDASeq", "edge", "edgeR", "effects", "eha", "ellipsis", "feather", "fftw",
  "fields", "forecast", "future.batchtools", "gamlss", "gamlss.dist",
  "gcrma", "genefilter", "geneplotter", "GenomeInfoDb", "GenomeInfoDbData",
  "GenomicAlignments", "GenomicFeatures", "GenomicRanges", "geometry",
  "ggformula", "ggstance", "ggvis", "GO.db", "graph", "gRbase", "gstat",
  "HDF5Array", "hdf5r", "hms", "htmlTable", "htmltools", "htmlwidgets",
  "httpuv", "huge", "hypergraph", "Icens", "impute", "IRanges",
  "ITALICSData", "jomo", "jpeg", "keras", "knitr", "lambda.r", "later",
  "lavaan", "lfa", "libcoin", "limma", "littler", "loa", "logspline", "LPE",
  "lpSolve", "makecdfenv", "maptools", "marray", "matrixStats", "MergeMaid",
  "Mfuzz", "microbenchmark", "miscTools", "ncdf4", "oligoClasses", "OLIN",
  "OpenMx", "openxlsx", "optparse", "OrderedList", "org.Hs.eg.db",
  "ParallelLogger", "partitions", "pbapply", "pcaMethods", "pkgbuild",
  "pkgconfig", "plm", "plotmo", "pls", "pmml", "polspline", "preprocessCore",
  "promises", "purrr", "qvalue", "qvcalc", "R.devices", "R.rsp", "rama",
  "raster", "RbcBook1", "RBGL", "Rcmdr", "RcppArmadillo", "recipes",
  "regtools", "rgdal", "rgeos", "rgl", "Rglpk", "RgoogleMaps", "Rgraphviz",
  "rhdf5", "Rhdf5lib", "Rhtslib", "rjags", "RJSONIO", "rlang", "Rmalschains",
  "rmarkdown", "RODBC", "RPMG", "Rsamtools", "RSEIS", "rtracklayer",
  "RUVSeq", "Ryacas", "rzmq", "S4Vectors", "semTools", "seqLogo",
  "seriation", "Seurat", "sf", "SGL", "shiny", "ShortRead",
  "SingleCellExperiment", "slam", "snm", "SNPchip", "spam", "spate",
  "spatstat", "spData", "spdep", "StanHeaders", "strucchange",
  "SummarizedExperiment", "sva", "svd", "sys", "tensorflow", "testit",
  "tidyr", "tinytex", "tkWidgets", "tmle", "TTR", "twilight", "TypeInfo",
  "units", "uroot", "vegan", "visNetwork", "whisker", "widgetTools", "xfun",
  "XVector", "zip", "zlibbioc"
), update = TRUE, ask = FALSE)
