---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    code_download: TRUE
    
params:
  dataset: baron 
  title: "Analysis of the Baron dataset"
---
---
title: `r params$title`
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.width = 5, fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "clusterExperiment", "mclust", "RColorBrewer", "purrr", "Dune",
          "png")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
source(here("Rmd", "helper.R"))
ref_clusters <- read.csv(here("data", params$dataset,
                              paste0(params$dataset, "_meta.csv"))) %>%
  arrange(X) %>%
  `$`("cell_type1") %>%
  as.numeric()
```

# EDA

We can first visualize the data after dimension reduction with zinbWave. We then use t-SNE and color the cells with the allen labels. Since we use various values for the k parameter, we plot two representations with the most extreme values of k.

```{r t-SNE plots, fig.width=18, fig.height=9}
plots <- list.files(here("Figures", "EDA"))
plots <- plots[str_detect(plots, params$dataset)]
plots <- plots[str_detect(plots, "png")]
plot.new()
plot.window(0:1, 0:1)
rasterImage(readPNG(here("Figures", "EDA", plots[1])), 0, 0, .5, 1)
rasterImage(readPNG(here("Figures", "EDA", plots[length(plots)])), 0.5, 0, 1, 1)
```

# 3 comparisons
## Comp1

```{r comp1}
walk(plot_all(dataset = params$dataset, comp = "comp1", ref = ref_clusters),
     print)
```

## Comp2

```{r comp2}
walk(plot_all(dataset = params$dataset, comp = "comp2", ref = ref_clusters),
     print)
```

## Comp3

```{r comp3}
walk(plot_all(dataset = params$dataset, comp = "comp3", ref = ref_clusters),
     print)
```

